// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.31.1
// source: api/proto/agent_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// 1. التسجيل
	RegisterAgent(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 2. البحث
	FindAgent(ctx context.Context, in *FindAgentRequest, opts ...grpc.CallOption) (*FindAgentResponse, error)
	// 3. إرسال نبضة دورية لتحديث الحالة
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// 4. إرسال تقرير بقواعد جدار الحماية
	ReportFirewallStatus(ctx context.Context, in *FirewallStatusRequest, opts ...grpc.CallOption) (*FirewallStatusResponse, error)
	// 5. إرسال تقرير بالتطبيقات المثبتة
	ReportInstalledApps(ctx context.Context, in *InstalledAppsRequest, opts ...grpc.CallOption) (*InstalledAppsResponse, error)
	// --------------------------- SERVICES (متعلق السيرفر يرسل للوكيل) ---------------------------
	// لم يتم التنفيذ بعد
	// 6. تكوين جدار الحماية: السيرفر يرسل أمر للوكيل لتعديل إعدادات جدار الحماية
	ConfigureFirewall(ctx context.Context, in *FirewallConfigurationRequest, opts ...grpc.CallOption) (*FirewallConfigurationResponse, error)
	// نفتح  قناة اتصال ثنائية الاتجاه
	TaskChannel(ctx context.Context, opts ...grpc.CallOption) (AgentService_TaskChannelClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RegisterAgent(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/proto.AgentService/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FindAgent(ctx context.Context, in *FindAgentRequest, opts ...grpc.CallOption) (*FindAgentResponse, error) {
	out := new(FindAgentResponse)
	err := c.cc.Invoke(ctx, "/proto.AgentService/FindAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/proto.AgentService/SendHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportFirewallStatus(ctx context.Context, in *FirewallStatusRequest, opts ...grpc.CallOption) (*FirewallStatusResponse, error) {
	out := new(FirewallStatusResponse)
	err := c.cc.Invoke(ctx, "/proto.AgentService/ReportFirewallStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportInstalledApps(ctx context.Context, in *InstalledAppsRequest, opts ...grpc.CallOption) (*InstalledAppsResponse, error) {
	out := new(InstalledAppsResponse)
	err := c.cc.Invoke(ctx, "/proto.AgentService/ReportInstalledApps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ConfigureFirewall(ctx context.Context, in *FirewallConfigurationRequest, opts ...grpc.CallOption) (*FirewallConfigurationResponse, error) {
	out := new(FirewallConfigurationResponse)
	err := c.cc.Invoke(ctx, "/proto.AgentService/ConfigureFirewall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) TaskChannel(ctx context.Context, opts ...grpc.CallOption) (AgentService_TaskChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], "/proto.AgentService/TaskChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceTaskChannelClient{stream}
	return x, nil
}

type AgentService_TaskChannelClient interface {
	Send(*TaskResult) error
	Recv() (*TaskRequest, error)
	grpc.ClientStream
}

type agentServiceTaskChannelClient struct {
	grpc.ClientStream
}

func (x *agentServiceTaskChannelClient) Send(m *TaskResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceTaskChannelClient) Recv() (*TaskRequest, error) {
	m := new(TaskRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// 1. التسجيل
	RegisterAgent(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 2. البحث
	FindAgent(context.Context, *FindAgentRequest) (*FindAgentResponse, error)
	// 3. إرسال نبضة دورية لتحديث الحالة
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// 4. إرسال تقرير بقواعد جدار الحماية
	ReportFirewallStatus(context.Context, *FirewallStatusRequest) (*FirewallStatusResponse, error)
	// 5. إرسال تقرير بالتطبيقات المثبتة
	ReportInstalledApps(context.Context, *InstalledAppsRequest) (*InstalledAppsResponse, error)
	// --------------------------- SERVICES (متعلق السيرفر يرسل للوكيل) ---------------------------
	// لم يتم التنفيذ بعد
	// 6. تكوين جدار الحماية: السيرفر يرسل أمر للوكيل لتعديل إعدادات جدار الحماية
	ConfigureFirewall(context.Context, *FirewallConfigurationRequest) (*FirewallConfigurationResponse, error)
	// نفتح  قناة اتصال ثنائية الاتجاه
	TaskChannel(AgentService_TaskChannelServer) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) RegisterAgent(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAgentServiceServer) FindAgent(context.Context, *FindAgentRequest) (*FindAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAgent not implemented")
}
func (UnimplementedAgentServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedAgentServiceServer) ReportFirewallStatus(context.Context, *FirewallStatusRequest) (*FirewallStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportFirewallStatus not implemented")
}
func (UnimplementedAgentServiceServer) ReportInstalledApps(context.Context, *InstalledAppsRequest) (*InstalledAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportInstalledApps not implemented")
}
func (UnimplementedAgentServiceServer) ConfigureFirewall(context.Context, *FirewallConfigurationRequest) (*FirewallConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureFirewall not implemented")
}
func (UnimplementedAgentServiceServer) TaskChannel(AgentService_TaskChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method TaskChannel not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AgentService/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterAgent(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FindAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FindAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AgentService/FindAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FindAgent(ctx, req.(*FindAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AgentService/SendHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportFirewallStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportFirewallStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AgentService/ReportFirewallStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportFirewallStatus(ctx, req.(*FirewallStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportInstalledApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstalledAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportInstalledApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AgentService/ReportInstalledApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportInstalledApps(ctx, req.(*InstalledAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ConfigureFirewall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ConfigureFirewall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AgentService/ConfigureFirewall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ConfigureFirewall(ctx, req.(*FirewallConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_TaskChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).TaskChannel(&agentServiceTaskChannelServer{stream})
}

type AgentService_TaskChannelServer interface {
	Send(*TaskRequest) error
	Recv() (*TaskResult, error)
	grpc.ServerStream
}

type agentServiceTaskChannelServer struct {
	grpc.ServerStream
}

func (x *agentServiceTaskChannelServer) Send(m *TaskRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceTaskChannelServer) Recv() (*TaskResult, error) {
	m := new(TaskResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AgentService_RegisterAgent_Handler,
		},
		{
			MethodName: "FindAgent",
			Handler:    _AgentService_FindAgent_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _AgentService_SendHeartbeat_Handler,
		},
		{
			MethodName: "ReportFirewallStatus",
			Handler:    _AgentService_ReportFirewallStatus_Handler,
		},
		{
			MethodName: "ReportInstalledApps",
			Handler:    _AgentService_ReportInstalledApps_Handler,
		},
		{
			MethodName: "ConfigureFirewall",
			Handler:    _AgentService_ConfigureFirewall_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TaskChannel",
			Handler:       _AgentService_TaskChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/agent_service.proto",
}
